version: "3.2"
services:
  redis:
    image: "redis"

    command: redis-server --requirepass  redis --appendonly yes

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/data

    environment:
      - REDIS_REPLICATION_MODE=master
